@startuml

hide members

abstract class AbstractBird
abstract class AbstractFlyableBird
abstract class AbstractUnFlyableBird

abstract class AbstractFlyableTweetableBird
abstract class AbstractFlyableUnTweetableBird
abstract class AbstractUnFlyableTweetableBird
abstract class AbstractUnFlyableUnTweetableBird

AbstractBird <|-- AbstractFlyableBird
AbstractBird <|-- AbstractUnFlyableBird

AbstractFlyableBird <|-- AbstractFlyableTweetableBird
AbstractFlyableBird <|-- AbstractFlyableUnTweetableBird

AbstractUnFlyableBird <|-- AbstractUnFlyableTweetableBird
AbstractUnFlyableBird <|-- AbstractUnFlyableUnTweetableBird

@enduml
