@startuml

class ApiRequest {
    -{static} long DEFAULT_TIME_INTERVAL = 1 * 60 * 1000
    - String token
    - long createTime
    - long expiredTimeInterval = DEFAULT_TIME_INTERVAL

    +{static} AuthToken create(String baseUrl, long createTime, Map<String, String> params)
    + String getToken()
    + boolean isExpired()
    + boolean match(AuthToken authToken)
}

@enduml
